### ISSUE TITLE
Superman: Man of Steel

### ISSUE THREAD

**Issue by dylanegan** [lstoll/Veranstaltungen#1]
http://www.cinestar.de/de/kino/berlin-cinestar-original-im-sony-center/kinoprogramm/man-of-steel. Thinking June 19.

/cc @Berlin/clique

**Comment by lstoll** [comment]
That's the day I ✈ to SFO, but don't let that stop you.

**Comment by dylanegan** [comment]
:cool: :story: :bro:

**Comment by ally** [comment]
YES YES YES

![tumblr_mn7g9vwt2x1rw29eto5_r1_400](https://f.cloud.github.com/assets/74259/596377/10fed196-cb88-11e2-8f52-a97e51e3dfc7.gif)

**Comment by ghost** [comment]
YES

**Comment by rkh** [comment]
Should be back in town. /cc @MariaKaline

**Comment by ghost** [comment]
I kinda wish I could spend my every day in spandex secretly saving the world.

**Comment by dylanegan** [comment]
OK. I have purchased :ticket: :ticket: :ticket: :ticket: :ticket: :ticket: (six tickets).

**Comment by dylanegan** [comment]
Please :+1: if you're in. Otherwise I'll find some other people who might be interested.

**Comment by dylanegan** [comment]
Oh also, I need to print them.

**Comment by kch** [comment]
Not sure i can commit that far ahead. Tentative :+1:

**Comment by kch** [comment]
I can print in the cowork if you don't have a printer.

**Comment by kch** [comment]
But TBH if you just show up and show them on your phone it's fine too. Did it a couple times.

**Comment by dylanegan** [comment]
Yeah, I was thinking about just doing that, but fuck :evergreen_tree:s.

**Comment by ally** [comment]
Oops, forgot to reply in a timely fashion.

:thumbsup:

**Comment by ally** [comment]
My friend Andrea would be in, if there are any spares...

**Comment by dylanegan** [comment]
@ally added her to the list.

**Comment by kch** [comment]
:+1: :+1: (that's ag and I.)

What's the time?

**Comment by dylanegan** [comment]
OK so have
- @ally 
- @ally's friend Andrea
- @codenamejac 
- @dylanegan
- @kch 
- Someone who isn't on GitHub, namely Agata.

Time is at 20:15 I think. June 19.

**Comment by dylanegan** [comment]
I have a friend (@jamiegirl1) in town who wants to join us. Since I lost my wallet I am unable to buy a ticket online. Would someone be able to pick one up? We're in B14-B19 if there are seats nearby.

**Comment by dylanegan** [comment]
OK committed people just remember that Obama is in town and he's staying in Potsdamer Platz so there might be a bit of a crazy time.

**Comment by ghost** [comment]
Are we meeting for grub prior or post or not at all?

**Comment by ghost** [comment]
Hey, is Jamie still in town? I thought she was leaving today? Also, where is the movie?

**Comment by jamiegirl1** [comment]
I am not. :) but hi!

Sent from my iPhone

Please pardon any typos.

**Comment by kch** [comment]
I'm down for eats.

**Comment by dylanegan** [comment]
I say [Corroboree](http://www.corroboree.info/Corroboree.html). :wink:

**Comment by ghost** [comment]
pies and snags?

**Comment by kch** [comment]
before or after? before is more likely, right?

**Comment by ghost** [comment]
yea the movie won't finish until 10-11pm.

**Comment by ally** [comment]
Some suggestions for food nearby:

There's a Thai restaurant kind of nearby http://www.edds-thairestaurant.de/ - I've never been, but I've heard it's pretty good. (It's a bit pricey though.) 

Also nearby: http://www.maultaschen-manufaktur.de/. They serve those German maultaschen (enormous ravioli type things). Pretty nice. Outdoor tables.

My favourite place of the moment is Jäger und Sammler, but it's further away than the other two. Food is fucking great though http://www.jaegerundsammler-berlin.de/index.php?id=2

**Comment by dylanegan** [comment]
:+1: to Jäger & Sammler.

**Comment by kch** [comment]
Need res? 18:30 gives us enough time?

**Comment by ally** [comment]
I can reserve... how many will come, anyone know? 6.30 should be enough time... film starts at 8.15 but there's always at least half an hour of ads.

**Comment by dylanegan** [comment]
Let's just assume 6 people.

**Comment by ally** [comment]
including me and andrea?

**Comment by dylanegan** [comment]
Ja. I only have 6 tickets for the movie.

**Comment by ally** [comment]
ok!

**Comment by ally** [comment]
Left a message to reserve, they not there until 6. But shouldn't be any problem - I've been there at that time before and it's always pretty empty early on.

**Comment by dylanegan** [comment]
![](http://upload.wikimedia.org/wikipedia/commons/8/8d/President_Barack_Obama.jpg)

If it is busy then I blame that buy.

**Comment by kch** [comment]
Remind me to tell at dinner the experience that was staying at the intercontinental at the same time as obama.

**Comment by dylanegan** [comment]
Just set one in [Reminders.app](http://en.wikipedia.org/wiki/Reminders_%28application%29).

**Comment by ghost** [comment]
When you look up the restaurant on maps there are 2; Grunewaldstraße 81 and Gleditschstraße 37.

any idea which one?

**Comment by ally** [comment]
Grunewaldstraße

**Comment by dylanegan** [comment]
If anyone has the 3D glasses at home you should bring them. I have three pairs.

**Comment by ghost** [comment]
I think we have more in storage too.

Thanks Ally for the info! See you guys there!

**Comment by dylanegan** [comment]
:superman: more like :muscular man:.
