### ISSUE TITLE
Pacific Rim

### ISSUE THREAD

**Issue by dylanegan** [lstoll/Veranstaltungen#11]
[Pacific Rim at Cinestar](http://www.cinestar.de/de/kino/berlin-cinestar-original-im-sony-center/kinoprogramm/pacific-rim), opening July 18. From the director of Pan's Labyrinth. 3D ACTION MOVIE FOR THE BIG SCREEN!

[8.0 on imdb](http://www.imdb.com/title/tt1663662/?ref_=sr_1).

> Fuck Avatar, THIS is what giant screens and 3D was made for. /via John
> 
> Far, far better than it had any right to be. And the 3d actually looked great! /via Glen
> 
> Nerd out on Robots VS Kaiju!!! AWESOME ACTION /via Marc

[EXPLOSIONS](https://www.youtube.com/watch?v=v7ssUivM-eM)

**Comment by dylanegan** [comment]
> Pacific Rim is the best action movie in at least 5 years easily. /via [@danwrong](https://twitter.com/danwrong/status/356149637683478528)

**Comment by sabman** [comment]
:+1: 
![EXPLOSIONS!](http://media.avclub.com/images/articles/article/64/64455/money_jpg_627x1000_q85.jpg)

**Comment by dylanegan** [comment]
Looking at heading to the IMAX session on Sonntagabend at 19:30. Anyone else interested?

**Comment by MariaKaline** [comment]
I thought on Sunday would be a Bowling session and something else (i.e. drinks) afterwards to celebrate? :(

**Comment by dylanegan** [comment]
I thought maybe pre-bowling at Antlered as per #9? There's a viewing on Montag, but I won't be able to do activities on both days.

**Comment by MariaKaline** [comment]
ah ok, I see

**Comment by dylanegan** [comment]
Ja. Going to pick up a couple (for @sabman and me) of tickets to the 19:30 session.

**Comment by sabman** [comment]
Given #9 is Sunday, anyone up for Monday?

**Comment by dylanegan** [comment]
Moving this to next week when @sabman returns from Lisbon for those who may be interested.

**Comment by kch** [comment]
I can maybe go next week. Are you buying tickets much ahead of time?

**Comment by sabman** [comment]
Thanks i am back morning of 3rd if ur feeling impatient ... Try to control
urselves

Sent from my iPhone

On 22.07.2013, at 17:59, Dylan Egan notifications@github.com wrote:

Moving this to next week when @sabman https://github.com/sabman returns
from Lisbon for those who may be interested.

—
Reply to this email directly or view it on
GitHubhttps://github.com/Berlin/Veranstaltungen/issues/11#issuecomment-21354156
.

**Comment by dylanegan** [comment]
@sabman 3rd, not the 31st anymore?

@kch probably, but depends on date and time.

**Comment by sabman** [comment]
Ya spending a few more days - the fish beckons! Sorry

Sent from my iPhone

On 23.07.2013, at 12:47, Dylan Egan notifications@github.com wrote:

@sabman https://github.com/sabman 3rd, not the 31st anymore?

@kch https://github.com/kch probably, but depends on date and time.

—
Reply to this email directly or view it on
GitHubhttps://github.com/Berlin/Veranstaltungen/issues/11#issuecomment-21408607
.
