### ISSUE TITLE
Sarod & Tabla

### ISSUE THREAD

**Issue by sabman** [lstoll/Veranstaltungen#13]
Mindpirates Wed 21st 9pm a friend and I have a gig
http://mindpirates.org/thelovers/?p=99

**Comment by dylanegan** [comment]
:+1: in!

**Comment by sabman** [comment]
So the location is Mindpirates
Schlesische Strasse 38, 3HH, 10997 Berlin
Starts 21:00 on wednesday

**Comment by dylanegan** [comment]
Awesome sauce dude. Totally need to bring weed next time.
