### ISSUE TITLE
Katz Orange and Neue Odessa

### ISSUE THREAD

**Issue by dylanegan** [lstoll/Veranstaltungen#15]
So tomorrow night is burger night at Katz Orange. I think. If not there are fucking amazing dishes regardless.

Also Tony from Antlered Bunny will be doing a shift at [Neue Odessa](http://www.neueodessabar.de) because they're off on their Christmas party.

/cc @Berlin/clique

**Comment by joshk** [comment]
I'm in!

**Comment by ghost** [comment]
ME TOO! Who needs to do work when you can eat lobster and drink cocktails?

**Comment by dylanegan** [comment]
OK, so just @codenamejac, @joshk and me?

/cc @Berlin/clique

**Comment by ghost** [comment]
I would love to but I just had another project land on my lap for this week, so I officially cannot have a social life. 

SORRY

**Comment by joshk** [comment]
What time you fellas wanna meet up?

**Comment by dylanegan** [comment]
@codenamejac just need to learn to manage and delegate.

@joshk I'm thinking we can dinner around 19:30. I'll wait until 17:00 for final numbers.

**Comment by ghost** [comment]
Delegate to whom? Future me? Cause that's what I'm doing, but there is only so many hours in a day.

**Comment by joshk** [comment]
Sounds good to me, I think Agata was interested in joining too.

**Comment by dylanegan** [comment]
@codenamejac yep, that's how it works.

**Comment by dylanegan** [comment]
@joshk plans changed, she might join us after.

**Comment by ghost** [comment]
it would if all my deadlines weren't this week. next week should be much calmer.

**Comment by lstoll** [comment]
Did I get uninvited?

**Comment by dylanegan** [comment]
@lstoll, nope, just going off of GitHub RSVPs. I didn't book anything so just going to rock up as they usually have the courtyard available.

**Comment by lstoll** [comment]
Cool. Still 1930?

**Comment by ghost** [comment]
Can you guys doggy bag me some ribs, chips and a cocktail?

**Comment by dylanegan** [comment]
@lstoll ja.

![](http://www.lolbrary.com/fullsize/518/fullsize-her-milkshake-brought-them-47518.jpg)

**Comment by dylanegan** [comment]
Jazz under the bridge. NAILED IT!
