### ISSUE TITLE
Naschmarkt 1. Sept

### ISSUE THREAD

**Issue by MariaKaline** [lstoll/Veranstaltungen#16]
Next Sunday will be the quarterly Naschmarkt with locally manufactured sweets. Here are the details:

Berliner Naschmarkt
Sonntag, 1. September 2013
12 bis 18 Uhr
Markthalle Neun
Eisenbahnstr. 42/43
10997 Berlin (Kreuzberg)

For further info see here: http://naschmarkt-berlin.de/?page_id=1067

**Comment by lstoll** [comment]
:+1: sounds good to me.

**Comment by dylanegan** [comment]
:+1:

:candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy: :candy:

**Comment by dylanegan** [comment]
![](http://24.media.tumblr.com/tumblr_lxsx0gulfV1r3asd3o1_400.gif)

**Comment by dylanegan** [comment]
![](http://bartlettsblueberryfarm.com/Bartlett's%20Blueberry%20Farm%20Facts_files/Blueberries%2520in%2520dew_lg.jpg)
