### ISSUE TITLE
Trio Rosenrot (Deutsche Volkslieder) 8 Sept

### ISSUE THREAD

**Issue by sabman** [lstoll/Veranstaltungen#17]
Live at Fincan on Sunday 8th September 8pm

Trio Rosenrot (Deutsche Volkslieder) live at Fincan, Berlin. German Folk music with a lovely vocalist. I know the Guitarist he's damn good and the drummer sounds superb too... checkout http://snd.sc/142y83w

more info at http://triorosenrot.com/live.htm and https://www.facebook.com/events/158697484335608/

**Comment by dylanegan** [comment]
You gotta CC that shit. /cc @Berlin/clique

**Comment by sabman** [comment]
:disappointed_relieved:  :ambulance:
