### ISSUE TITLE
Taste The Doom 11

### ISSUE THREAD

**Issue by dylanegan** [lstoll/Veranstaltungen#18]
I will finally be in town for one of these events and it seems to be the best one so far.

September 7 at Prinzessinnengarten. Please RSVP by midday Saturday so I know how many tickets to book.

/cc @Berlin/clique 

/via https://github.com/Berlin/Veranstaltungen/issues/6#issuecomment-23275872

**Comment by lstoll** [comment]
I'm in.

**Comment by joshk** [comment]
I have no idea what this is, but I'm in (unless is it mega expensive)

**Comment by dylanegan** [comment]
They moved their ticket sales forward so I have reserved three tickets so far.

**Comment by dylanegan** [comment]
Well I have requested 3 tickets. Whether or not I get them is another matter.

**Comment by dylanegan** [comment]
See everyone on Saturday.

@joshk I owe you 5 euros as these tickets are 25 euros each.

**Comment by dylanegan** [comment]
This starts at 19:00 so be sure to be on time.
