### ISSUE TITLE
Dos Palillos Third Birthday

### ISSUE THREAD

**Issue by dylanegan** [lstoll/Veranstaltungen#2]
So (Dos Palillos](http://www.dospalillos.com/home.php?rest=2&lang=en) are having their third birthday on June 27 (it was actually in January). I need to RSVP this week I think. 60 euros per person for food and drinks and stuff.

/cc @Berlin/clique

**Comment by kch** [comment]
:+1: 

is that all I need to do?

**Comment by dylanegan** [comment]
@kch ja. @codenamejac, about to email them, you in?

**Comment by ally** [comment]
I'm in!

Also, this looks good: http://junggrunblau.com

**Comment by dylanegan** [comment]
OK, emailed them.

**Comment by kch** [comment]
agata +1'd but refuses to get on gh.

**Comment by sabman** [comment]
:+1:

**Comment by dylanegan** [comment]
OK, we're in for six people. It starts at 18:00. Not really sure of the food situation, but apparently they're grilling (as well?).
- @ally 
- @codenamejac
- @dylanegan
- @kch 
- @kch +1
- @sabman

**Comment by dylanegan** [comment]
@codenamejac you be in?

**Comment by ghost** [comment]
DON'T FORGET MEEEEEEEEEE

On 18 June 2013 17:37, Dylan Egan notifications@github.com wrote:

> @codenamejac https://github.com/codenamejac you be in?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/Berlin/Veranstaltungen/issues/2#issuecomment-19619666
> .

## 

Kind Regards,

Jacqui

**Comment by ghost** [comment]
DON'T FORGET ME!

On 18 June 2013 17:37, Dylan Egan notifications@github.com wrote:

> @codenamejac https://github.com/codenamejac you be in?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/Berlin/Veranstaltungen/issues/2#issuecomment-19619666
> .

## 

Kind Regards,

Jacqui

**Comment by dylanegan** [comment]
Landed. See y'all soon. It starts at 18:00

**Comment by dylanegan** [comment]
Running late from TXL. Also no need to rush as it should hopefully run for a few hours (food wise) I hope.

**Comment by kch** [comment]
Do we have a table, or is it a standing thing, or what?

**Comment by ghost** [comment]
I wouldn't wear your good heels if I were you. 

There were reservations so I assume there is a table. But who knows.

**Comment by ghost** [comment]
Anyone there yet? I didn't bring a book to read and there is a man in there
with hairplugs

**Comment by dylanegan** [comment]
:hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger: :hamburger:
