### ISSUE TITLE
Nachtmarkt, 12 September

### ISSUE THREAD

**Issue by dylanegan** [lstoll/Veranstaltungen#20]
/cc @Berlin/clique @benschwarz @timriley

As there'll be people popping in to town over the coming days.

If anything I'll be going at 18:00 to avoid the crowd.

**Comment by timriley** [comment]
@garmisch and I are keen!

**Comment by dylanegan** [comment]
So I might have to bail to get some stuff done this evening. I think @sabman is interested, as well as @benschwarz.

**Comment by sabman** [comment]
Got x-fit at 7.15 just up the road on Mortizplatz, maybe I'll come say hi or just come after the workout. will ping @timriley

**Comment by benschwarz** [comment]
STOP

```
—
```

**Comment by benschwarz** [comment]
Erm, yeah I'm in. Meet at 6ish ?

```
—
```

**Comment by lstoll** [comment]
Weird, muting wfm.

**Comment by ghost** [comment]
MUTE MORE

**Comment by ally** [comment]
I can't tonight, boo.

**Comment by timriley** [comment]
Just for the record, @garmisch and I will be there at 6. FOOOD.

**Comment by rkh** [comment]
> STOP

![hammer time](http://www.manaleak.com/mtguk/files/2011/08/hammer-time.jpg)

Anyway, waiting for @MariaKaline, if she's in time we could join.

**Comment by joshk** [comment]
Sadly I can't come tonight, work phone calls and all that fun stuff. Enjoy.

**Comment by rkh** [comment]
OK, I'm in, beaches.

**Comment by timriley** [comment]
We'll be there at 6:30.

**Comment by dylanegan** [comment]
I'll be at home with a bottle of wine.

https://www.youtube.com/watch?v=EzoazPPC7b8
