### ISSUE TITLE
Braufest

### ISSUE THREAD

**Issue by dylanegan** [lstoll/Veranstaltungen#21]
[Braufest](http://www.braufest-berlin.de/de/programm.html).

Tomorrow and Saturday. /cc @Berlin/homies @benschwarz @timriley

**Comment by joshk** [comment]
Yum, beer!

**Comment by adelcambre** [comment]
Should we hit this up tonight? Also, Jan told me to bring everyone to the JSConf party tonight, starts at 9pm.

**Comment by benschwarz** [comment]
See you at the party. We're drinking now at antlered bunny

—

**Comment by adelcambre** [comment]
You eat yet? I'm starving. @jsncostello and @rsanheim are passed out. I'll come by antlered bunny.
