### ISSUE TITLE
Dos Palillos Lunch & Antlered Bunny Oysters

### ISSUE THREAD

**Issue by dylanegan** [lstoll/Veranstaltungen#22]
On Saturday. Bloody Mary menu.

/cc @Berlin/homies @benschwarz @timriley

**Comment by joshk** [comment]
Yum, oysters!

**Comment by sabman** [comment]
:+1: + sarah to confirm (only lunch I think)

**Comment by timriley** [comment]
@garmisch and I are in! Let us know when :)

**Comment by dylanegan** [comment]
12:30 for Dos!

**Comment by benschwarz** [comment]
Ok. I'll do it… because it sounds like I shouldn't miss out.

**Comment by will** [comment]
is it at  Weinmeisterstraße 1, 10178 ?

**Comment by will** [comment]
when is oysters?

**Comment by dylanegan** [comment]
@will they start from 14:00 onwards.

**Comment by dylanegan** [comment]
Just getting ready to head across to Dos.

**Comment by dylanegan** [comment]
Wow, pretty much nailed that.

Shots, bowling and teleportation.
