### ISSUE TITLE
Wasserschlacht

### ISSUE THREAD

**Issue by rkh** [lstoll/Veranstaltungen#23]
The Wasserschlacht (F'hain vs Xberg) is this sunday.
- http://www.mo-berlin.com/wasserschlacht-auf-der-oberbaumbruecke-2013/
- http://de.wikipedia.org/wiki/Gem%C3%BCseschlacht_(Berlin)
- http://www.xhain.info/wasserschlacht/
- http://www.youtube.com/watch?v=BU3D7FaMHTM

**Comment by lstoll** [comment]
Ridiculous

**Comment by rkh** [comment]
> Surprisingly, Friedrichshain have won every single year bar one, when back in 2011 Kreuzberg claimed victory for the first time. Their time at the top was short lived however, as last year Friedrichshain reclaimed superiority when they showed up with larger numbers and more brutal force, which led them once again to push their way into Kreuzberg to win the battle.

**Comment by dgoodlad** [comment]
Incredible. Should be funny in the rain!

**Comment by sabman** [comment]
This year X'berg may win if @lstoll joins their ranks
