### ISSUE TITLE
BBQ, Cocktails and Bowling

### ISSUE THREAD

**Issue by dylanegan** [lstoll/Veranstaltungen#24]
I get back in on Friday night and pending my current health I'd be up for some Saturday fun.

/cc @Berlin/clique

**Comment by joshk** [comment]
:fist:

**Comment by lstoll** [comment]
:-1:, Chez Maman time.

**Comment by dylanegan** [comment]
Definitely hitting up BBQ, but not sure about the rest as still not 100%.

Will be at BBQ around 12:30/13:00 when brisket should be tender.

**Comment by joshk** [comment]
Is BBQ now? drat.
