### ISSUE TITLE
DINE like you meant it

### ISSUE THREAD

**Issue by dylanegan** [lstoll/Veranstaltungen#25]
[DINE like you mean it](https://www.facebook.com/events/1398150773755339/).

> We can keep a secret and we hope that you can too. KAFFEEBAR is just about ready to welcome its big, grown up sister into the neighborhood. Before opening the gourmet eatery next January, however, we’d like to grant a few lucky patrons a sneak-peak into the not-yet renovated location during our month-long pop up dinner series, "DINE like you mean it".
> 
> Adding to the clandestine affair, we’ve invited a top-level chef to join our ranks and whip up a seasonal, fresh, and rustic-gourmet menu for our pop up guests. Too shy and humble to divulge his name just yet, the lauded gourmet cook recently made his move from the prize-winning Frankfurt kitchens to spread his love for delectably inventive dishes to Berlin. We’re proud he’s joining us and can’t wait to shout his name from the Kreuzberg rooftops. 
> 
> Every Friday and Saturday until the end of November, 20 guests will be served a delicious, seasonal three-course menu, aperitivo and espresso included, in the cozy, candle-lit confines of our new location. To join, please send a private message to Kaffeebar’s Facebook page, complete with the date you’d like to attend:
> 
> November 1+2, 8+9, 15+16, 21+22
> 
> Dinner starts at 20.00 and the location and menu will be revealed to reserved guests two days prior to the date. costs: 35 Euro

**Comment by lstoll** [comment]
I'd be down for 21+22, or 16. Don't land 'til 1830 on 15th.

**Comment by dylanegan** [comment]
Yeah, could look at that. I guess I need to /cc @Berlin/clique

**Comment by rkh** [comment]
Sounds good. /cc @MariaKaline

**Comment by joshk** [comment]
16th would be good for me, not sure if I will still be around the follow weekend.

**Comment by dylanegan** [comment]
So 16th could be possible for @lstoll too I guess. @rkh what dates work for you?

I assume they haven't been booked out so will contact them as soon as possible.

**Comment by vmg** [comment]
IM DOWN

**Comment by rkh** [comment]
@dylanegan ALL THE DATES.

Or rather: CHECK WITH @MariaKaline!

**Comment by dylanegan** [comment]
BOOKED OUT!

They are opening up some other dates, but they are TBA.

**Comment by dylanegan** [comment]
We actually got offered a table, but unfortunately we couldn't take it. I'm assuming they'll still open up other dates.

**Comment by dylanegan** [comment]
We've been given the option of doing it on the 29th, but we're booked in for #35. Hopefully they extend if another week.

**Comment by dylanegan** [comment]
I assume they're done for the year. I'll reopen if they contact me again.
