### ISSUE TITLE
Cheese Berlin

### ISSUE THREAD

**Issue by dylanegan** [lstoll/Veranstaltungen#26]
[03/11/2013](http://cheese-berlin.de/cheese-berlin/).

/cc @Berlin/clique

**Comment by norbert** [comment]
+1

**Comment by joshk** [comment]
Yum

**Comment by rkh** [comment]
What time are you going?

/cc @chad

**Comment by chad** [comment]
We will be flying back from Dublin :'(

**Comment by dylanegan** [comment]
Going to aim for 11:00 with @MariaKaline and @rkh.

**Comment by dylanegan** [comment]
CHEESECAKE CHEESE CHEESECAKE!

![](http://i1046.photobucket.com/albums/b469/dryedmangoezsunny/five/sunny505-00014.jpg)
