### ISSUE TITLE
Bowling & Slowlands

### ISSUE THREAD

**Issue by dylanegan** [lstoll/Veranstaltungen#27]
Friday, 8th November. Pre-whisky Disco Bowling.

![](https://partywirks.com/asset/asset/2975/glow_3.jpg?1207252810)

Then Slowlands.

> 22.00 hrs on Friday 8th Nov. 2013 // Elsenstrasse 52, 2nd
> backyard, 2nd floor
> Music provided by Slowlands Berlin’s Music Department residents Fearplay and
> Pure.
> 
> As always we’ll treat you with a unique selection of rare single-casks and
> limited editions of liquid gold from all corners of this world and a
> blissfully-slow-yet-slightly-crushing-turning-heavy-and-complex music mix.
> we are truly looking forward to see you!

**Comment by joshk** [comment]
:+1:

**Comment by dylanegan** [comment]
I believe @MariaKaline and @rkh are in. @MariaKaline is making a reservation for bowling so I guess we'll start with one lane.

**Comment by MariaKaline** [comment]
yes, I will make a reservation. Would 8.15 PM be good for y'all?

//cc @chad + Kelly

**Comment by dylanegan** [comment]
Also @sabman is in so I guess that'll probably be cause for two lanes if @chad is in.

**Comment by chad** [comment]
:+1:  I think @kellyjeanne and I will be there.

**Comment by dylanegan** [comment]
@MariaKaline Agata and @kch are in I think. Or at least Agata will be.

**Comment by joshk** [comment]
I am in too! :)

**Comment by dylanegan** [comment]
Also @codenamejac is in.

**Comment by MariaKaline** [comment]
I made a reservation for 2 lanes for 8.30 PM. Here is the address:

BOWLERO - Bowlingcenter
Samariterstrasse 19 - 20, 
10247 Berlin - Friedrichshain

**Comment by dylanegan** [comment]
/cc @ally

ALSO FUCK YEAH DISCO BOWLING!

**Comment by dylanegan** [comment]
@MariaKaline also made an event on [Facebook](https://www.facebook.com/events/629546730429869).

**Comment by dylanegan** [comment]
![](http://i.imgur.com/mm6WxQC.gif)

**Comment by dylanegan** [comment]
![](http://i.imgur.com/v7d1p4p.gif)

**Comment by dylanegan** [comment]
Saugeil!

**Comment by dylanegan** [comment]
Totally nailed Slowlands. Also 150, fuck yeah!
