### ISSUE TITLE
Dinner at Schneeweiß, Discobowling 2.0 or Lasertag and maybe Karaoke

### ISSUE THREAD

**Issue by MariaKaline** [lstoll/Veranstaltungen#29]
So this was an awesome weekend! Time to plan the next one. Thinking about doing this on Saturday. Preferences concerning Discobowling or Lasertag?

**Comment by vmg** [comment]
Lasertag sounds **_awesome**_. I'm down for both though.

**Comment by dylanegan** [comment]
Let's see what lasertag places are open in Berlin.
- [LasergGame](http://www.spielt-lasertag.de/en).

Also [strippers](http://www.spielt-lasertag.de/en/gallery/striptease-girls/). I am so confused.

> Stag parties can book a stripshow additionally to the game – please ask for details.

**Comment by dylanegan** [comment]
Also /cc @Berlin/clique

**Comment by joshk** [comment]
BOTH SOUND AWESOME!

**Comment by jfryman** [comment]
Nice! @azizshamim and I will be in town Thursday - Sunday, with a conference somewhere in there on Friday. I'm game.

**Comment by lstoll** [comment]
There's also [Underground Lasergame](http://www.undergroundlasergame.de). It's UNDERGROUND. [They also can organise a strip show](http://www.undergroundlasergame.de/jungges)

**Comment by MariaKaline** [comment]
strip show? are you American or what?! :P 

Both Lasertag places look great. But also, our Discobowling place is awesome as well. We could also do these sports on different days.

so as soon as you agreed on when you want to eat, what you wanna play, when you wanna start playing and how long you want to play, I can make arrangements. And I would need a preferably definite number of people playing.

**Comment by azizshamim** [comment]
ooooh.. @lstoll i think she called you an american... or a what... them's DRINKING words...

**Comment by kch** [comment]
also wanna throw go karts in the mix, but let's do that once I'm back. Namely after dec 20.

**Comment by rkh** [comment]
> Also wanna throw go karts in the mix, but let's do that once I'm back. Namely after dec 20.

Oh yes! I'm up for that.

**Comment by lstoll** [comment]
Go Kart in the snow.

But seriously, you can just do that in the streets: http://www.berlin.kart4you.de

**Comment by lstoll** [comment]
@MariaKaline @azizshamim I thought that was more of a British thing anyway?

**Comment by rkh** [comment]
> But seriously, you can just do that in the streets: http://www.berlin.kart4you.de

![image](https://f.cloud.github.com/assets/30442/1518896/40657978-4b47-11e3-8ced-f4a6e00c6753.png)

> @MariaKaline @azizshamim I thought that was more of a British thing anyway?

I mean, you should know.

**Comment by dylanegan** [comment]
- @MariaKaline 
- @rkh 
- @vmg 
- @joshk 
- @jfryman 
- @lstoll (maybe @codenamejac)
- @kch
- @azizshamim 
- @dylanegan

@MariaKaline wants to book stuff in. I reckon we aim for Lasertag, but given that it is Wednesday they might be booked up.

**Comment by rkh** [comment]
Saturday?

**Comment by vmg** [comment]
Y E S

**Comment by sabman** [comment]
Am I too late to the party? :worried: ... :+1: if still possible

**Comment by MariaKaline** [comment]
@sabman Don't worry, I counted you in :) Do you wanna come to dinner as well?

So guys, I got an answer from Underground Lasergame and they are booked out all Saturday and Sunday. They do have a spot on Friday (15.11.) starting from 8.30 till 10 PM But I'm not sure whether to book it or not because some of you will be just arriving on Friday, right?

The other Lasertag place hasn't replied yet, so it's still pending what we'll gonna do on Saturday. Bu we'll defintely do something!

I'll keep you posted!

**Comment by sabman** [comment]
@MariaKaline vielen danke! No dinner for me...will join you all after dinner

**Comment by MariaKaline** [comment]
ok, apperently all people in Berlin wanna do something on Saturday  but don't you worry I managed to get reservations anyways!

So on Saturday Dinner at Schneeweiß starts at 6.30 PM. (We could also get the table at 6 PM if you like?) 
Here's the address:

Schneeweiß Berlin
Simplonstraße 16
10245 Berlin

We could have the table till 9.30 PM. But we should leave earlier because I made a reservation for 2 lanes for Discobowling starting at 9 PM. We're doing this in a different place than usual because our standard bowling place already had a 100 person reservation. The new location is:

Eastside Bowling
Koppenstraße 8
10243 Berlin

Xtreme Discobowling will start at 10 PM, so we'll have an hour to warm up.

**Comment by dylanegan** [comment]
![](http://eil.com/images/main/Vanilla+Ice+-+To+The+Extreme+-+CD+ALBUM-306152.jpg)

**Comment by dylanegan** [comment]
http://www.youtube.com/watch?v=P0baLMn2EE0

**Comment by MariaKaline** [comment]
CHANGE OF PLANS! BE PREPARED TO HAVE TO MOST FUCKING AWESOME SATURDAY EVER!!!

Here's the plan:
Dinner at Schneeweiß: 6 PM (we can and should be there at 5.30 PM so we don't have to rush and have a relaxed look at the menue)
Lasertag: 8 - 9.30 PM (@sabman we all need to be there 15 minutes early, so please keep that in mind. That's the place we're gonna lasertag: http://www.spielt-lasertag.de/en)
XTREME Discobowling: 10.30 PM - open end

How does that sound? I know it's a tight schedule but apparently all companys do their Christmas partys in the next weeks, so it will be hard to get any reservation. So we should make this happen. What do you say? Are you good with that?

**Comment by dylanegan** [comment]
:+1: ALL THE WAY BABE!

**Comment by dylanegan** [comment]
SAUGEIL!

**Comment by dylanegan** [comment]
![](http://i580.photobucket.com/albums/ss242/Unreal_Dj/Metal-Horns-explosion.gif)

**Comment by vmg** [comment]
OH SHIT BABY IM SO DOWN FOR THIS

**Comment by sabman** [comment]
MARK ME DOWN!

**Comment by joshk** [comment]
I’M IN!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

On 14 November 2013 at 5:00:09 pm, Shoaib Burq (notifications@github.com) wrote:

MARK ME DOWN!

**Comment by rkh** [comment]
Hmm... is it strange that the part that I find the most extreme about this plan is dinner at 5.30? ;)

**Comment by rkh** [comment]
![](http://25.media.tumblr.com/5365233a326347fa49788935151fc4be/tumblr_mssu7yEZo71svpvevo4_250.gif)
![](http://25.media.tumblr.com/ee0ac4f61c0ed71d2c18c7e7a3e2f98e/tumblr_mssu7yEZo71svpvevo9_r2_250.gif)

**Comment by lstoll** [comment]
@dylanegan was you listing my naming before counting me in, or just a ping? I thought it was listing in, but want to check.

**Comment by dylanegan** [comment]
@lstoll I think it included you in. @MariaKaline knows the numbers. If you can't make it we can adjust.

**Comment by MariaKaline** [comment]
@lstoll I counted you in. Including myself we're 12 people playing lasertag. If someone decided not to come it would be nice to tell me in advance, so I can make adjustments. Thanks!

**Comment by rkh** [comment]
They asked us to make sure everyone has read this:

http://www.spielt-lasertag.de/en/lasertag/checklist/

**Comment by sabman** [comment]
@MariaKaline http://www.youtube.com/watch?v=g0p6VtgxbH0

**Comment by rkh** [comment]
Reminder:
- Laser Tag is 30 € per person
- You need to bring an ID
- They recommend bringing another shirt in case we get all sweaty at laster tag
- Bowling is 15 € per lane per hour (we have two lanes, plus 1.50 for shoes)

**Comment by lstoll** [comment]
Also, if you're **not** coming now would be a great time to say - it looks like we have to pay regardless if you show up or not at lasertag.

I think the confirmed list is @azizshamim @MariaKaline @vmg @joshk @jfryman @kch @codenamejac @rkh @dylanegan @sabman . Plus Agata. Why isn't Agata on GitHub?

**Comment by dylanegan** [comment]
Also will be at Antlered Bunny before Schneeweiß (around 14:00 onwards) if anyone wants a drink and some oysters.

**Comment by rkh** [comment]
> Also will be at Antlered Bunny before Schneeweiß (around 14:00 onwards) if anyone wants a drink and some oysters.

Might join you later.

**Comment by kch** [comment]
If agata had a job in tech, maybe she'd be forced to have a githubs. Wink wink nudge nudge.

**Comment by kch** [comment]
As far as dinner 1730, I'm so not having lunch.

**Comment by rkh** [comment]
> As far as dinner 1730, I'm so not having lunch.

I think that's the generally agreed upon strategy.

**Comment by dylanegan** [comment]
SURPRISE BUNNY AND KARAOKE!

**Comment by jfryman** [comment]
BEST SATURDAY IN BERLIN EVER. WOULD BERLIN AGAIN! A+++++

Thanks for the good times, all. Glad I was able to meet you all and hang out. Enjoyed it immensely. :beers:

**Comment by azizshamim** [comment]
ich war ein berliner... and it was awesome. Thank you @MariaKaline for organizing it all and to the rest of you for being such wonderful hosts.

~~Aziz's Rule #723 - Aziz does not vacation in Germany~~

**Comment by MariaKaline** [comment]
So happy that you guys came along! Hope you got to the airport alright? Let me know in advance when you're coming back to Berlin so I can plan an even more awesome night!
Also love the no-rule#723 :)
