### ISSUE TITLE
Kreativ Tage Berlin 15.-17. November

### ISSUE THREAD

**Issue by MariaKaline** [lstoll/Veranstaltungen#30]
Anyone wants to go there with me, have a look and get inspired? You can also buy some stuff to get creative. I think this might be interesting especially for @codenamejac and @kellyjeanne?

http://www.kreativ-tage-berlin.de/start.html

**Comment by kellyjeanne** [comment]
When are you going?

**Comment by MariaKaline** [comment]
they open every day 11 AM. I think I would like to go on Saturday because I don't know how long I would sleep in on Sunday because of Discobowling Saturday night. Btw, are you and @chad joining us?

So should we aim for 11 AM and maybe meet somewhere on the way? Also @codenamejac is coming with us.
I would take the Ringbahn S42 starting from Frankfurter Allee and get off at Messe Nord/ICC. What's your closest Ubahn/ Sbahn stop?

**Comment by MariaKaline** [comment]
So in case someone else wants to come along, @codenamejac and I are meeting 11.35 AM at S+U Gesundbrunnen track 2 and will leave for Messe Nord/ICC around 11.42 AM with S42
