### ISSUE TITLE
Lasertag Friday 15.11.2013

### ISSUE THREAD

**Issue by MariaKaline** [lstoll/Veranstaltungen#32]
So as I wrote in the other issue Underground Lasergame would have an open spot for Friday 8.30 till 10 PM. Should we use this or try to make Lasertag happen on the next weekend?
I would need to tell them today so it would be nice if you guys could give me an answer asap. Thx!

//cc @Berlin/clique

**Comment by joshk** [comment]
SWEET! LASERTAG!

That sounds awesome for next weekend!
On 14 November 2013 at 12:17:09 pm, MariaKaline (notifications@github.com) wrote:

So as I wrote in the other issue Underground Lasergame would have an open spot for Friday 8.30 till 10 PM. Should we use this or try to make Lasertag happen on the next weekend?
I would need to tell them today so it would be nice if you guys could give me an answer asap. Thx!

//cc @Berlin/clique

**Comment by sabman** [comment]
:+1:

**Comment by dylanegan** [comment]
Next weekend for mine.

**Comment by vmg** [comment]
Sure, next weekend.

**Comment by MariaKaline** [comment]
ok, can we do this on Friday November 22 then?

**Comment by vmg** [comment]
K A L I N E :shipit:

**Comment by dylanegan** [comment]
Let's plan for a game after the holidays.
