### ISSUE TITLE
Taste The Doom 13

### ISSUE THREAD

**Issue by dylanegan** [lstoll/Veranstaltungen#33]
So the [next TTD](http://tastethedoom.com/?p=293) has gone on sale today. Is anyone interested? Last time was really good.

**Comment by MariaKaline** [comment]
I would be interested. @rkh?

**Comment by rkh** [comment]
:+1:

**Comment by vmg** [comment]
Some background? What is this about? The website doesn't say anything.

**Comment by rkh** [comment]
> Some background? What is this about? The website doesn't say anything.

Yo momma doesn't say anything about it either.

**Comment by rkh** [comment]
It's whiskey.

**Comment by lstoll** [comment]
@rkh such an American

**Comment by rkh** [comment]
> @rkh such an American

_Puts on British accent._ Your dear mother is such an American. Let us drink whisky.

**Comment by dylanegan** [comment]
I didn't book anything. If anyone is interested you can get the email from the blog post.

**Comment by dylanegan** [comment]
They have some tickets, but we've got #37 tomorrow.

**Comment by MariaKaline** [comment]
It starts at 9 PM, right? We could do that also. We only have the table till 8.15 PM. @joshk what do you think?

**Comment by joshk** [comment]
TTD is great, but then we would have to give up on Xmas markets right?

**Comment by dylanegan** [comment]
Ja, plus not enough tickets for everyone. Plus no Glühwein!
