### ISSUE TITLE
Mikkeller Popup

### ISSUE THREAD

**Issue by dylanegan** [lstoll/Veranstaltungen#34]
http://mikkeller.dk/mikkeller-loves-berlin/ via @dylanfm.

**Comment by lstoll** [comment]
Definitely gonna hit this one up.

**Comment by dylanegan** [comment]
They came, they served, they didn't conquer.

**Comment by DylanFM** [comment]
No conquer? Good beers?

**Comment by dylanegan** [comment]
Ja. Sehr gut!

**Comment by lstoll** [comment]
The beer was delicious. Thanks for the heads up, @DylanFM !

**Comment by DylanFM** [comment]
Wunderbar!
