### ISSUE TITLE
Cheese and Wine

### ISSUE THREAD

**Issue by MariaKaline** [lstoll/Veranstaltungen#35]
The wine store where the Jung, Grün & Blau guys bought their wine is having cheese and wine tastings once a month. Next one would be November 29th. It's 39€/person. If you're interested in going we should make a reservation asap.

http://www.planet-weinhandel.de/angebot_3.htm

**Comment by MariaKaline** [comment]
So who's in? I would need to make a reservation.

/cc @Berlin/clique

**Comment by vmg** [comment]
That's right next to my place. I'm d o wn

**Comment by lstoll** [comment]
:+1:

**Comment by lstoll** [comment]
:+1: for @codenamejac

**Comment by dylanegan** [comment]
I AM ALL THE WAY IN! I AM IN SO DEEP!

Also I think Agata is in.

**Comment by lstoll** [comment]
@aszyma ^^

**Comment by joshk** [comment]
I'm in! That will be my last weekend in Berlin!

**Comment by rkh** [comment]
@norbert? Claudia?

**Comment by MariaKaline** [comment]
YEAH, JUST BOOKED IT! It's gonna be delicamazing! They also have lots of non-cow-lactose-cheese for @codenamejac.

So I believe we are 8 people now: me, @rkh, @codenamejac, @lstoll, @dylanegan, @vmg, @joshk, @aszyma. They would have space for 2 more people. who else is in?

If someone decides not to come, please tell me in advance, so the Planet Wein can give the reserved spots to others.

Also, it starts 8 PM. If you guys wanna get (a light) dinner before, let me know and I make reservations.

**Comment by vmg** [comment]
I know a couple people who may be interested if you want to fill those spots.

**Comment by ally** [comment]
Just realised my github email was still set to my old work address so I DIDN'T GET ANY OF THESE AMAZING NOTIFICATIONS.

Are there still places left? I'll take one if so...

**Comment by MariaKaline** [comment]
@ally you're a lucky girl because we have ONE spot left :) Looking forward to see you and the others tomorrow at 8 PM (or earlier for dinner?)

Here's the address again:

Planet Wein
Weinhandel am Gendarmenmarkt
Mohrenstraße 30
Eingang Charlottenstraße
10117 Berlin

P.S. Again, if someone decides not to come please make sure you have someone who would take the spot or we would need to pay for the person anyways and we wouldn't want that I guess. Thank you guys!

**Comment by ally** [comment]
@MariaKaline Yaaaaay thanks Maria! I don't think I'd have time for dinner beforehand... boo. I guess I'll have to eat enough cheese to serve as a meal.

**Comment by MariaKaline** [comment]
@ally you're welcome! we could bring you a burger if you like and you can have it just beforehand?

**Comment by ally** [comment]
@MariaKaline where are you going for burgers?

**Comment by lstoll** [comment]
S H I S O B U R G E R

**Comment by sabman** [comment]
Noice! I might drop in for a burger and a half

**Comment by dylanegan** [comment]
https://www.youtube.com/watch?v=2JcFtXnQwm8
