### ISSUE TITLE
Samstag aka We Get Rid Of @joshk Day!

### ISSUE THREAD

**Issue by dylanegan** [lstoll/Veranstaltungen#37]
So that guy, @joshk is leaving (hopefully for good).
- Aunt Benny for vegan chilli
- #34 
- [Lucia Weihnachtsmarkt](http://www.weihnachteninberlin.de/weihnachtsmaerkte/pankow/971171-1328139-luciaweihnachtsmarktinderkulturbrauerei.html)
- The Bird
- Antlered Bunny
- Orgy

**Comment by rkh** [comment]
> - Aunt Benny for vegan chilli
> - #34
> - Lucia Weihnachtsmarkt
> - The Bird
> - Antlered Bunny
> - Orgy

And, to relax after that:
- Bowling
- Booz Bar
- Käptn
- Feuermelder
- Karaoke

**Comment by dylanegan** [comment]
Ja. I believe @MariaKaline and @joshk have been organising The Bird and Bowlero.

**Comment by lstoll** [comment]
I'm looking forward to the farewell party with @roidrage on Dec 2.

I was going to be heading to Dortmund on Sat, but I'll push that back for this.

**Comment by dylanegan** [comment]
SO EXCITE TO GET RID OF @JOSHK!

**Comment by joshk** [comment]
;(

**Comment by dylanegan** [comment]
Heading over to Michelberger for some Mikkeller shortly.

**Comment by dylanegan** [comment]
Finally, over.

**Comment by joshk** [comment]
Thanks everyone for turning up, was awesome fun.
