### ISSUE TITLE
Inside Llewyn Davis

### ISSUE THREAD

**Issue by dylanegan** [lstoll/Veranstaltungen#38]
The latest [movie](https://en.wikipedia.org/wiki/Inside_Llewyn_Davis) from the Coen brothers.

Supposedly out December 5.

**Comment by rkh** [comment]
:+1:

**Comment by dylanegan** [comment]
The tickets are finally on sale at [Cinestar](http://www.cinestar.de/de/kino/berlin-cinestar-original-im-sony-center). I'm thinking either 19:30 on Donnerstag or sometime next week.

**Comment by rkh** [comment]
:+1:

**Comment by dylanegan** [comment]
Nächsten Dienstag um 19:30?

**Comment by rkh** [comment]
:+1: need to check if @MariaKaline is coming.

**Comment by dylanegan** [comment]
Moved to Donnerstag as per request from @rkh.

**Comment by rkh** [comment]
Woohoo! Who's in? Maria is not coming.

**Comment by sabman** [comment]
:+1: and sarah (maybe)

**Comment by dylanegan** [comment]
So the movie is only showing at 17:40 tomorrow. Which is quite annoying. Thoughts?

**Comment by rkh** [comment]
Hmpf.

**Comment by dylanegan** [comment]
Great thoughts. Will subscribe, but first I think we should push it back to next week. @codenamejac is still not 100%.

**Comment by dylanegan** [comment]
So Tuesday at 20:10. Who is in? I think I might get the tickets for it now just to prevent getting split seats.

**Comment by rkh** [comment]
I'm in yo. I think Maria isn't.

**Comment by ghost** [comment]
Can't make it on Tuesday. Have a good time, guys!

**Comment by dylanegan** [comment]
Bought tickets for @rkh and I. If you're interested we're sitting at A14, A13.

**Comment by rkh** [comment]
Sweet! Thanks. As in, first row?

**Comment by dylanegan** [comment]
I hope so!

**Comment by dylanegan** [comment]
Great movie. Just don't get caught up drinking beforehand. Also, rude Germans.
