### ISSUE TITLE
Closure of Spreepark

### ISSUE THREAD

**Issue by dylanegan** [lstoll/Veranstaltungen#4]
http://blog.inberlin.de/2013/05/sonderfuehrung-durch-den-spreepark-am-23-06-2013/. For anyone that is in town this Sunday.

**Comment by dylanegan** [comment]
This is now also on the 30th, this Sunday. I believe @MariaKaline and @rkh are heading. I'm :+1: too.

**Comment by rkh** [comment]
Confirm. Should we book together or should I just book for Maria and me?

**Comment by dylanegan** [comment]
Please to book for me.

**Comment by rkh** [comment]
OK, so three? Should we ask others? @Berlin/clique

**Comment by kch** [comment]
Ag and I too. :+1: :+1:

**Comment by norbert** [comment]
Possibly me as well, will let you know. Can highly recommend visiting the place either way.

**Comment by sabman** [comment]
:+1:

**Comment by rkh** [comment]
So, shall I book for six people? More?

**Comment by dylanegan** [comment]
:+1: for :six:. They be committed then!

**Comment by dylanegan** [comment]
@rkh is this one?

**Comment by rkh** [comment]
Yes, they didn't get back to me (even though they had a check box for getting a confirmation) so I contacted them today. We're all set. It's €20/person.

**Comment by rkh** [comment]
> Hallo Herr Haase,
> 
> wir haben sechs Teilnehmer vermerkt, hier nochmal alle Infos:
> 
> Hiermit bestätigen wir Ihre Teilnahme an folgender Tour:
> Bezahlung vor Ort, 20 Euro pro Person (Kinder bis 10 Jahre freier Eintritt), bitte dafür schon um 10:40 Uhr vor Ort sein.
> 
> Spreepark-Tour
> Datum/Uhrzeit: 30.06.2013 um 11 Uhr
> Treffpunkt: Besuchereingang vor dem Spreepark, Wasserweg –
> 12435 Berlin-Treptow (Google Maps Link: http://goo.gl/maps/6kPm3)
> bei Unklarheiten/Verspätung usw.: 0174-1574836
> 
> weitere Informationen unter:
> http://bit.ly/1aFoOTj
> 
> Bilder:
> http://bit.ly/172BIs4
>                                     ************************************
> 
> We hereby confirm your attendance at the following tour:
> Payment before the tour starts, EUR 20 per person (children up to 10 years free), therefore you must be there at 10:40 am.
> 
> Spreepark Tour
> Date / Time: 30.06.2013 at 11 clock am
> Meeting point: in front of the visitors' entrance Spreepark, Wasserweg -
> 12435 Berlin-Treptow (Google Maps link: http://goo.gl/maps/6kPm3)
> for clarification / delay etc.: 0174-1574836
> 
> more information:
> http://bit.ly/1aFoOTj
> 
> pictures:
> http://bit.ly/172BIs4
> 
> language: usually the tour is in German, we have an additional english speaking guide for this tour
> 
> Beste Grüße / Best regards
> Norbert Wollweber

I stated that we want an English guide.

**Comment by dylanegan** [comment]
:roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster: :ferris_wheel: :carousel_horse: :roller_coaster:

**Comment by norbert** [comment]
@rkh can you try adding two more to the reservation?

**Comment by rkh** [comment]
Sent them an email.

**Comment by rkh** [comment]
@norbert ok, all set

**Comment by dylanegan** [comment]
Meet at Plänterwald at 10:20 as we need to be there by 10:40.

**Comment by sabman** [comment]
http://instagram.com/p/bLkHd0tEcN/

**Comment by joshk** [comment]
:(
