### ISSUE TITLE
Gravity (IMAX 3D OV)

### ISSUE THREAD

**Issue by dylanegan** [lstoll/Veranstaltungen#42]
So I thought this movie had finished in IMAX, but it seems like there are still a few viewings left. There is one next Wednesday. /cc @codenamejac @rkh

**Comment by vmg** [comment]
+100, I've been wanting to watch this shit forever.

**Comment by lstoll** [comment]
We get back during the evening on Wed.

Is there one after that?

**Comment by dylanegan** [comment]
Looks like they actually removed it. I guess we just have to wait and see.

**Comment by dylanegan** [comment]
So it looks like there is now nothing except this evening on CineStar. It is at 23:15. /cc @vmg

**Comment by vmg** [comment]
You mean tonight?

**Comment by dylanegan** [comment]
@vmg yeah, the cinema is pretty empty.

![](http://f.cl.ly/items/3r0a1P443R2N1A3q173e/Screen%20Shot%202013-12-08%20at%2017.14.53%20.png)

**Comment by vmg** [comment]
Hm. This plan doesn't mix well with my intention of waking up at 7AM tomorrow because the goddamn landlady is coming. I'll have to pass. :/

**Comment by dylanegan** [comment]
No problem. Gives me more time for sleep. Or GTA V. Will reopen the issue if a viewing comes up.

**Comment by dylanegan** [comment]
So it seems that it most likely will not be shown in IMAX again. It is still showing in normal 3D. The Hobbit opens this week and looks like it'll be taking over IMAX for the most part.

**Comment by dylanegan** [comment]
There appears to be one viewing open on the 18/12 at 13:15.

**Comment by dylanegan** [comment]
![](http://cl.ly/image/302H3P2A3x1R/Screen%20Shot%202013-12-12%20at%2010.25.25%20.png)

**Comment by vmg** [comment]
Lunch & gravity?

**Comment by dylanegan** [comment]
Yeah, that would work. There is currently one person in that session. Guess we just buy it on the day.

**Comment by vmg** [comment]
Cool. Lunch? Not sure of what's a good food place close by.

**Comment by dylanegan** [comment]
Tim Raue? LOLOL

**Comment by dylanegan** [comment]
OK, so there are a few more seats sold which means the session will be on. Not sure where to lunch, but will find something.

**Comment by vmg** [comment]
Sounds good. I'm definitely down.

**Comment by rkh** [comment]
:+1:

**Comment by vmg** [comment]
What time are we meeting for lunch? 12:00? where?

**Comment by dylanegan** [comment]
Do you want to come around to ours? We have some leftovers and I'm thinking we'll do that and then head to Potsdamer Platz. Don't worry, there is meat. Think of it as a potluck.

**Comment by dylanegan** [comment]
Aight. @codenamejac and me are staying home for lunch. You're welcome to join us, say 12:00. Otherwise we'll catch you at the cinema.

**Comment by vmg** [comment]
Hmm. I'm very close to Potsdamer Platz so I think I'll lunch at home and head there directly too. :)

**Comment by dylanegan** [comment]
![](http://i.dailymail.co.uk/i/pix/2013/09/05/article-0-1BA4BDF4000005DC-6_634x278.jpg)
