### ISSUE TITLE
Weinnachtsmarkt, Saturday 14th

### ISSUE THREAD

**Issue by dylanegan** [lstoll/Veranstaltungen#44]
Anyone interested for this Saturday (late afternoon, early evening)?
- http://www.weihnachtsmarkt-deutschland.de/lehmanns-bauernhof-berlin.html
- Lucia (#37)
- http://weihnachtsmarkt-vor-dem-schloss-charlottenburg.de

Also post-Discobowling if there are lanes available.

**Comment by lstoll** [comment]
:+1:

**Comment by dylanegan** [comment]
@rkh any luck with the lanes?

**Comment by dylanegan** [comment]
Thinking about heading towards Schloss Charlottenburg since it is supposed to be quite good, plus Schloss. Aiming for early evening. Maybe grab food out there. Not sure. /cc @Berlin/clique

**Comment by ghost** [comment]
YES. What time about? And do you have something specific in mind for eats?

**Comment by rkh** [comment]
Wo geht?

**Comment by dylanegan** [comment]
Meeting @aszyma at U8 Weinmeisterstraße. Will probably grab Dada. Then U-Bahn/S-Bahn to Schloss.

**Comment by rkh** [comment]
OK, there's also Kiezweihnachtsmarkt only this weekend: http://www.kiezweihnacht.de/

**Comment by rkh** [comment]
We might stay in F'hain, because we're laaaaaaaaaazy.

**Comment by lstoll** [comment]
Booze Bar? :trollface:

**Comment by rkh** [comment]
Hehehe.

**Comment by dylanegan** [comment]
Schloss Charlottenburg was pretty awesome. Definitely need to hit it up again.
