### ISSUE TITLE
Berlinale

### ISSUE THREAD

**Issue by rkh** [lstoll/Veranstaltungen#46]
[Homepage](http://www.berlinale.de/en/HomePage.html).

Tickets go on sale next month, I think. Opening film is [The Grand Budapest Hotel](http://www.youtube.com/watch?v=1Fg5iWmQjwk).

**Comment by dylanegan** [comment]
Yes!

**Comment by sabman** [comment]
yes indeed!

**Comment by dylanegan** [comment]
@rkh looks like the programme opens up at the end of January so we should keep an eye out for tickets.

**Comment by sabman** [comment]
Think tickets should be available this coming week... according to the website: "The festival programme is published at the end of January, ca. one week prior to the beginning of the advance ticket sales."

**Comment by sabman** [comment]
sold out in 5min :crying_cat_face: 

 https://www.berlinale.de/en/programm/berlinale_programm/datenblatt.php?film_id=20146244#tab=filmStills

**Comment by dylanegan** [comment]
Online is limited so might have to pop in to one of the venues, but yeah. :crying_cat_face:

**Comment by rkh** [comment]
I have two tickets for the Budapest Hotel and am bidding on another two right now.

**Comment by dylanegan** [comment]
:+1:

**Comment by rkh** [comment]
I did not get the other tickets. So if anyone wants to join, you'll have to find tickets on your own somewhere.
