### ISSUE TITLE
Only Lovers Left Alive

### ISSUE THREAD

**Issue by rkh** [lstoll/Veranstaltungen#47]
Anyone wants to watch that movie next week-ish?

**Comment by dylanegan** [comment]
I'm in. /cc @katbudrys

**Comment by FloorD** [comment]
I'm in. @anikalindtner, @pxlpnk ?

**Comment by anikalindtner** [comment]
of course! (of course!)

**Comment by pxlpnk** [comment]
count me in!

**Comment by rkh** [comment]
@MariaKaline suggested Friday.

**Comment by dylanegan** [comment]
Out for Friday.
