### ISSUE TITLE
Jung Grün & Blau

### ISSUE THREAD

**Issue by dylanegan** [lstoll/Veranstaltungen#5]
I have a table for 6 on Wednesday July 17 at [Jung Grün & Blau](http://junggrunblau.com).
- @ally
- @dylanegan
- @codenamejac
- @lstoll 
- @rkh
- @sabman

**Comment by ally** [comment]
:thumbsup:

**Comment by rkh** [comment]
Confirm.

**Comment by dylanegan** [comment]
OK, still have one spot left. /cc @Berlin/clique

**Comment by rkh** [comment]
Quick reminder that I don't eat seafood.

**Comment by dylanegan** [comment]
@rkh emailed them. Still have one spot left. @ally, want to check with Andrea?

**Comment by dylanegan** [comment]
@rkh you're good for no seafood. I've given them my :phone: :hash: so they'll call closer to the date to give the location.

**Comment by rkh** [comment]
![](http://3.bp.blogspot.com/_iQTPQ0EPHEg/TPJ9FIrWDhI/AAAAAAAAAEI/u9dNhLx2EWM/s200/no%2Bfish4U.jpg)

**Comment by dylanegan** [comment]
@sabman are you in?

**Comment by sabman** [comment]
:+1:

**Comment by dylanegan** [comment]
OK so dinner is set. We can either meet there or grab a drink beforehand. I won't paste the address here so just hit me up when you need it, but please allow an hour to get there. It is north west of Tiergarten. It starts at 20:00.

**Comment by rkh** [comment]
Drink where? Green Door?

**Comment by dylanegan** [comment]
@rkh we could go over near the restaurant I guess. It is near Turmstraße U-Bahn.

**Comment by lstoll** [comment]
M O A B I T   lol

**Comment by MariaKaline** [comment]
Have you been to Turmstraße? It's so ghetto. I doubt there will be a nice bar for you guys.

**Comment by lstoll** [comment]
Vielleicht ein Sternburg Export bei einem Spätkauf dann.

**Comment by ally** [comment]
Ooo Berlin bier shop is just near there. And maybe a brewery..?

**Comment by ally** [comment]
We could go to the arminius markthalle, it's just near turmstraße. That Berlin brewery Brewbaker has a stand there, and there's some nice tables to sit and drink at.

**Comment by dylanegan** [comment]
:+1: to @ally's idea.

**Comment by rkh** [comment]
What time?

**Comment by dylanegan** [comment]
Whenever you want I guess. I'll probably be there around 19:30. The dinner should be about 5 minutes from the brewery.

**Comment by dylanegan** [comment]
Heading up to Moabit now.

**Comment by rkh** [comment]
WHY HAS THIS NOT BEEN CLOSED YET?

**Comment by dylanegan** [comment]
Because GitHub don't allow you to close from the mobile view.

Also amazing dinner. Fucking amazing dinner.
