### ISSUE TITLE
2-2: Ground Hog Day aka Maria's Birthday

### ISSUE THREAD

**Issue by rkh** [lstoll/Veranstaltungen#52]
The party will be taking place at Booze Bar in Friedrichshain, starting at 7pm. You are more than welcome to bring a plus one. Important: Maria has been dreaming of doing a proper themed party for quite some time now. So that's what we're gonna do. The theme is "The Roaring Twenties". If you don't find anything fitting, just dress up.

/cc @vmg @ally @norbert @Berlin/clique

**Comment by lstoll** [comment]
Booze Bar?

**Comment by rkh** [comment]
Booze Bar.

**Comment by vmg** [comment]
Amazzzzzing. I'm gonna be chilling the fuck out in the warm weather at home, but I'll try to facetime in to remind you how much I love you guise <3 <3 <3

**Comment by dylanegan** [comment]
![](http://media-cdn.tripadvisor.com/media/photo-s/01/f2/9d/34/booze-bar.jpg)
