### ISSUE TITLE
5 STERNE BURGER

### ISSUE THREAD

**Issue by dylanegan** [lstoll/Veranstaltungen#53]
[5 STERN BURGER](http://cargocollective.com/bestburgerberlin/5-STERNE-BURGER).

:star::star::star::star::star:

**Comment by lstoll** [comment]
All of them.

**Comment by rkh** [comment]
:+1: interesting that Burgerwehr and Frittiersalon aren't listed.

**Comment by rkh** [comment]
And they didn't really like Shiso Burger, it seems.

**Comment by lstoll** [comment]
They're good, but not 5*

Shiso is the underdog though.
