### ISSUE TITLE
The Grand Budapest Hotel

### ISSUE THREAD

**Issue by sabman** [lstoll/Veranstaltungen#55]
Opens 6th March
http://www.yorck.de/yorckplus/veranstaltungen/show/1107

Thinking about friday session. Lemme know if anyone's interested?

**Comment by dylanegan** [comment]
@katbudrys and myself. Is this OV and OV only? Or German subs?

**Comment by sabman** [comment]
good point... will call em and find out tonight

**Comment by sabman** [comment]
with DE subs :disappointed:

**Comment by sabman** [comment]
looks like all of them have de subs. http://www.yorck.de/film/detail/109645

**Comment by dylanegan** [comment]
@sabman ah, I would probably only go to an OV session. Maybe just have to cinestar it?
