### ISSUE TITLE
Schnitzel, Schnitzel

### ISSUE THREAD

**Issue by rkh** [lstoll/Veranstaltungen#56]
Anyone up for Schneeweiß? I hear a few people are in town for various reasons.

@deadprogram @steveklabnik @dgoodlad @roidrage @svenfuchs

![](http://stream1.gifsoup.com/view/603807/schnitzel-man-1-o.gif)

https://www.youtube.com/watch?v=zra4iXz-LKU

**Comment by rkh** [comment]
Oh also: @brianmario

**Comment by deadprogram** [comment]
Ya das ist gut! cc/ @zankich

**Comment by deadprogram** [comment]
Me so hungry!

**Comment by rkh** [comment]
Ah, oh, sorry, I wasn't thinking today. I can't today. :(

**Comment by deadprogram** [comment]
I was thinking tomorrow night, actually :goat:

**Comment by rkh** [comment]
Ah, cool, yes, I'll call them tomorrow during the day. This place needs a reservation, usually. I hear @dgoodlad is in, too. Maybe @vmg, also? I don't think @steveklabnik is in town yet, though.

**Comment by zankich** [comment]
I'm down for tomorrow

**Comment by rkh** [comment]
We're talking dinner, right?

**Comment by deadprogram** [comment]
Yes!

**Comment by rkh** [comment]
Hmm. They are completely booked for tomorrow and are closed on Thursday, which is a public holiday. For some reason, they are also closed on Saturday.

**Comment by deadprogram** [comment]
Alas, poor Schnitzel. Schneeweiß looks awesome. I suppose we need an alternative, then.

**Comment by rkh** [comment]
How about http://www.katzorange.com/en? It's a bit more upscale (and a bit more pricey for Berlin standards).

**Comment by rkh** [comment]
Alternative would be to go less fancy, grab burgers or something. I don't think we need a reservation for less fancy. :)

**Comment by deadprogram** [comment]
Looks tasty, I'm in.

**Comment by deadprogram** [comment]
Any of the above is good for me, anyplace you like is probably great.

**Comment by rkh** [comment]
Any preferred time?

**Comment by deadprogram** [comment]
Whatever is the "normal" dinner hour in Berlin, or alternatively whatever time you like.

**Comment by rkh** [comment]
OK, booked a table for 7pm.
