### ISSUE TITLE
Berlin Festival, 5-7 Sep

### ISSUE THREAD

**Issue by lstoll** [lstoll/Veranstaltungen#57]
Has Moderat and Trentemøller, [amongst others](http://www.berlinfestival.de/en/acts/line-up.html). They're both on Sunday, so could probably grab a [Day ticket for Sunday](http://www.berlinfestival.de/en/tickets.html) for like €~50 to check it out.

**Comment by lstoll** [comment]
zomg just saw [Mount Kimbie are there too](http://www.berlinfestival.de/acts/artists-a-z/act/mount-kimbie.html).

/cc @dylanegan @benschwarz

**Comment by lstoll** [comment]
Oh and maybe @sr

**Comment by benschwarz** [comment]
Trentmøller, Kimbie, Onra, Moderat, Darkside… holy shit. 

5—7 in Berlin works for me… If the trip plans out, I'm hoping to be there for the 12th anyway!

**Comment by dylanegan** [comment]
Hot damn that's a lineup. /cc @dylanfm

**Comment by sr** [comment]
Ninaaaaa!!! Magdaaaaaa! Ellennnnn!!

**Comment by DylanFM** [comment]
🎉💻🎶!!

**Comment by lstoll** [comment]
Tickets purchase for @lstoll, @dylanegan @katbudrys @saltinejustine. Y'all better get on this soon.

**Comment by benschwarz** [comment]
Did you get a Sunday ticket @lstoll?

**Comment by lstoll** [comment]
Bought the 72 hour ticket or whatever the 'whole weekend' one was, there is some stuff I wanted to check on Saturday too.

**Comment by benschwarz** [comment]
Sweet

**Comment by benschwarz** [comment]
Stuff I wanna see: 
- Darkside - Friday 00:45 - 01:45
- Todd Terje - Friday 02:00 — 03:10
- Jacques Green - Friday 02:00 — 03:15
- Hudson Mohawk - Friday 03:15 — 04:30
- Mount Kimbie — Saturday 21:30 — 22:30
- Onra - Saturday 23:45 — 01:00
- Moderat - Sunday — 22:00 — 23:15

Probably a couple of others… but yeah, if we're gonna go, this is what I wanna see. 

+@geelen

**Comment by dylanegan** [comment]
@benschwarz bought tickets yet? :wink:

**Comment by benschwarz** [comment]
Naw. Not yet

**Comment by katbudrys** [comment]
:+1: 

Sounds good. Excited! 
Hope you guys get tickets!

**Comment by dylanegan** [comment]
FUCK YES! NAILED IT!
