### ISSUE TITLE
Yasuragi Hasseludden

### ISSUE THREAD

**Issue by lstoll** [lstoll/Veranstaltungen#59]
Just because we didn't go to True North doesn't mean we can't hang out in a Japanese Spa for a weekend.

Not sure when yet, but maybe late summer?

/cc @sr @dylanegan

**Comment by sr** [comment]
That'd be real good yeah... Maybe more around the winter though? Nothing like sitting in the hot bath with snow and freezing air temperature. Plus it's great to cope with SAD.
