### ISSUE TITLE
Theme Park with Aiden

### ISSUE THREAD

**Issue by rkh** [lstoll/Veranstaltungen#60]
We gotta go to a theme park and take Aiden. Preferably on a Wednesday.

/cc @lstoll @MariaKaline @BanzaiMan @SaltineJustine

**Comment by BanzaiMan** [comment]
Needless to say, I'm :+1:.

**Comment by ctrlaltjustine** [comment]
Obviously :+1::+1::+1:

**Comment by lstoll** [comment]
I’ll more than likely have to work, or be on call - so have to count me out :(

**Comment by rkh** [comment]
Possible parks:
- [Heide-Park Soltau](http://www.heide-park.de/en/heide-park/). Three hours by car, five by train (because middle of nowhere). 85 ha.
- [Europapark](http://www.europapark.de/). In the Black Forest, largest in continental Europe. Seven hours by car or train. 94 ha.
- [Belantis](http://www.belantis.de/index.php?id=5&L=1). Near Leipzig. Two hours by car, a bit less by train. 27 ha.
- [Hansapark](http://www.hansapark.de/en/), located at the Baltic Sea. Three hours by car, three and a half by train. 46 ha.
- [The real Legoland](http://www.legoland.dk/en/). In Denmark. Six hours by car. 3.8 ha.
- [Filmpark Babelsberg](http://www.filmpark-babelsberg.de/start-en.html). In Potsdam. 40 minutes on the S-Bahn. Does not have larger rides. Small.
- [Phantasialand](http://www.phantasialand.de/en/home). Near Cologne. Six hours by car or train. 28 ha.
- [Silesian Amusement Park](http://www.wesole-miasteczko.pl/www/en/). In Poland. Five hours by car. 25 ha (largest in Poland).

More on [Wikipedia](http://en.wikipedia.org/wiki/List_of_amusement_parks_in_Europe#.C2.A0Germany).

Plus the abandoned Spreepark in Berlin.

Maria points out that we could also do the weekend, since most kids have school holidays right now, so there won't be much of a difference.

**Comment by rkh** [comment]
Date/park suggestions?

**Comment by rkh** [comment]
Most parks also come with hotels for overnight stays.

**Comment by BanzaiMan** [comment]
I think Hansa-Park would be the best among these, when we factor in distance and value. (Proximity to the sea is also a plus.)

**Comment by pedro** [comment]
wow, EPIC!
so what is ha? heh.

I'm taking vacation in Iceland next week so wouldn't be able to make it until July 30th :{ but sign me up if you are going after that!

**Comment by BanzaiMan** [comment]
This will have to happen before 28th.

**Comment by pedro** [comment]
right on. will be waiting for a detailed report then! :}

**Comment by rkh** [comment]
ha = hectare (10,000 square metres)

**Comment by BanzaiMan** [comment]
If weekend means a merrier travel, does Saturday next week (26 July) work for everyone?

**Comment by BanzaiMan** [comment]
If not, Friday (25 July)?

**Comment by ctrlaltjustine** [comment]
I think I'm going to have to skip this unfortunately :( But take lots and lots of photos of Aiden going nuts for me!

**Comment by rkh** [comment]
NEVER!
