### ISSUE TITLE
Matürlich Saturday Brunch

### ISSUE THREAD

**Issue by dylanegan** [lstoll/Veranstaltungen#7]
[Brunch at Mercosy](https://www.facebook.com/events/513872388667618/?ref=22).

**Comment by joshk** [comment]
Who is going to brunch today? I would be interested in joining if others are heading that way.

**Comment by dylanegan** [comment]
Going to be there around 13:00.

**Comment by joshk** [comment]
I might run a little late, is that going to be alright?

**Comment by dylanegan** [comment]
Walking there now from Markthalle Neun.

**Comment by joshk** [comment]
Just you? If I am there at 1:30 is that too late?

**Comment by dylanegan** [comment]
@joshk perfect. With others.

**Comment by joshk** [comment]
sorry, i didn't hear from you so I didn't leave yet, i think it will take me about 40mins to get there, that puts it at 2, if that is an issue just say, sorry for all this
