### ISSUE TITLE
Bowling

### ISSUE THREAD

**Issue by dylanegan** [lstoll/Veranstaltungen#9]
Sunday bowling, maybe a monthly thing. Brunch at Aunt Benny/Antlered Bunny followed by bowling. Sonntag 21 Juli?

/cc @Berlin/clique

**Comment by rkh** [comment]
+:100:

**Comment by MariaKaline** [comment]
So what's the plan? (late) morning bowling session and lunch at aunt benny or brunch and bowling afterwards?

**Comment by dylanegan** [comment]
I like how we did last time. Brunch and bowling. I'm easy to do early bowling followed by lunch though.

**Comment by anikalindtner** [comment]
coffee at aunt benny? i'm so there :)

**Comment by MariaKaline** [comment]
so tomorrow 12 PM at Aunt Benny and afterwards bowling? who's in? should we make a reservation?

**Comment by anikalindtner** [comment]
hej, i'm in for coffee at aunt bennys :)

**Comment by dylanegan** [comment]
Heading over shortly. I'll try and convince people on the way.

**Comment by dylanegan** [comment]
:champion:
